apiVersion: apps/v1
kind: Deployment
metadata:
  name: misc-new
  namespace: misc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-new-misc
  template:
    metadata:
      labels:
        app: httpd-new-misc
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
          - containerPort: 80