apiVersion: apps/v1
kind: Deployment
metadata:
  name: misc-new-misc
  namespace: misc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80