apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm-charts/nginx
      sourceRef:
        kind: GitRepository
        name: k8s-deploy
      interval: 1m