apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
 name: nginx-qa
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/nginx
      sourceRef:
          kind: GitRepository
          name: k8s-deploy
          namespace: flux-system
      interval: 1m
  releaseName: nginx-qa
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFiles:
    - values.yaml
